# Generated by Django 4.2.2 on 2023-07-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='games',
            name='imagen',
            field=models.ImageField(null=True, upload_to='games/'),
        ),
    ]
